### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by ivybridge-3c33** [Zemelia/express-react-view-engine#3]
Please help me fix this error when use import

`SyntaxError: Unexpected token import
at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.require.extensions.(anonymous function) [as .jsx] (/node_modules/node-jsx/index.js:26:12)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at View.renderFile [as engine] (/node_modules/express-react-view-engine/index.js:63:25)
    at View.render (/node_modules/express/lib/view.js:135:8)
    at tryRender (/node_modules/express/lib/application.js:640:10)
    at Function.render (/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/node_modules/express/lib/response.js:1008:7)
    at render (/app/controllers/web/testController.js:4:16)
    at tryCatch (/node_modules/regenerator-runtime/runtime.js:62:40)
`

**Comment by Zemelia** [comment]
Hello, sorry, this fork out of date and it doesn't supported. You should look on original repo.
